services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: dev
    env_file:
      - ./server/.env
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
      - /app/node_modules
    command: pnpm start:dev

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: dev
    env_file:
      - ./client/.env.local
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
    command: pnpm dev -- -H 0.0.0.0 -p 3000
